# Generated by Django 4.2.2 on 2023-07-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_distribution_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
