# Generated by Django 4.2.2 on 2023-07-10 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_alter_distribution_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
